export const START_GET_WORLD_DATA = 'START_GET_WORLD_DATA';
export const SUCCES_GET_WORLD_DATA = 'SUCCES_GET_WORLD_DATA';
export const ERROR_GET_WORLD_DATA = 'ERROR_GET_WORLD_DATA';

export const START_SEARCH_COUNTRY_DATA = 'START_SEARCH_COUNTRY_DATA';
export const SUCCES_SEARCH_COUNTRY_DATA = 'SUCCES_SEARCH_COUNTRY_DATA';
export const ERROR_SEARCH_COUNTRY_DATA = 'ERROR_SEARCH_COUNTRY_DATA';

// TABLE SECTION
export const START_GET_TABLE_SECTION_DATA = 'START_GET_TABLE_SECTION_DATA';
export const SUCCES_GET_TABLE_SECTION_DATA = 'SUCCES_GET_TABLE_SECTION_DATA';
export const ERROR_GET_TABLE_SECTION_DATA = 'ERROR_GET_TABLE_SECTION_DATA';
